source "https://rubygems.org"

ruby "3.3.5"

gem "rails", "~> 8.0.1"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "redis", "~> 5.3"
gem "sidekiq", "~> 7.3"
gem "aws-sdk-s3", "~> 1.178"
gem "rack-cors", "~> 2.0.1"
gem "tzinfo-data", platforms: %i[x86_64-linux aarch64-linux]
